const menuList = [
    {
        title:'首页',
        key:'/home',
        icon:'home',
    },{
        title:'商户管理',
        key:'/merchants',
        icon:'solution',
        children:[
            {
                title:'商户列表',
                key:'/merchant',
                icon:'table'
            },{
                title:'添加商户',
                key:'/addMerchant',
                icon:'user-add'
            }
        ]
    },{
        title:'渠道管理',
        key:'/channels',
        icon:'deployment-unit',
        children:[
            {
                title:'渠道列表',
                key:'/channel',
                icon:'table'
            },{
                title:'添加渠道',
                key:'/addChannel',
                icon:'plus-square'
            }
        ]
    },{
        title:'订单管理',
        key:'/orders',
        icon:'file',
        children:[
            {
                title:'交易明细',
                key:'/order',
                icon:'table'
            },{
                title:'代付明细',
                key:'/proxyOrder',
                icon:'table'
            }
        ]
    },{
        title:'系统管理',
        key:'/systems',
        icon:'setting',
        children:[
            {
                title:'修改密码',
                key:'/system',
                icon:'security-scan'
            }
        ]
    }
]
export default menuList